export enum Role {
  FARMER = 'FARMER',
  CONTRACTOR = 'CONTRACTOR',
  TRACTOR_OWNER = 'TRACTOR_OWNER',
  SKILLED_WORKER = 'SKILLED_WORKER',
  EQUIPMENT_OWNER = 'EQUIPMENT_OWNER',
  SUPPLIER = 'SUPPLIER',
  ADMIN = 'ADMIN',
}
